export const colors = {
  primary: "#5D5FEF",
  lightPrimary: "#9FA1F4",
  darkPrimary: "#2F31BE",
  primary_100: "#A2A3F7",
  primaryContrast: "#EFFFF2",
  secondary: "#FF7D1F",
  error: "#FF735E",
  info: "#7484FC",
  success: "#81E542",
  warning: "#FCDA00",
  borderColor: "#D7DBE8",
  backgroundColor: "#FFFFFF",
  headingColor: "#1F2937",
  black: "#000000",
  white: "#FFFFFF",
  red: "#FF0000",
  green: "#24CB43",
  darkGreen : "#007515",
  gray: "#9C9E9D",
  lightGray: "#F3F3F3",
  info100: "#7484fc1a",
  disabled: "#6F6F6F",
  rejected: "#C4C4C4",
  leadsCardBg: "#646bffe0",

  tint: "#e0e1f9",
  tint02: "#FBFCFE",

  text01: "#1A1D1B",
  text02: "#464D55",
  text03: "#1a1d1b66",
  text04: "#1a1d1b33",
  text05: "#1a1d1b1a"
}

export const images = {
  homeBg: require('../assets/images/home-bg.png'),
  forgotPassword: require('../assets/images/forgot-password.png'),
  leadsBg: require('../assets/images/leads-bg.png'),
  logo: require('../assets/images/logo.png'),
  logoGreen: require('../assets/images/logo-green.png'),
  dummyAvatar: require('../assets/images/dummy-avatar.png'),
}

export const icons = {
  user: require('../assets/icons/user.png'),
  userOutline: require('../assets/icons/user-outline.png'),
  email: require('../assets/icons/email.png'),
  emailOutline: require('../assets/icons/email-outline.png'),
  lock: require('../assets/icons/lock.png'),
  phone: require('../assets/icons/phone.png'),
  check: require('../assets/icons/check.png'),
  visibility: require('../assets/icons/visibility.png'),
  visibilityOff: require('../assets/icons/visibility-off.png'),
  company: require('../assets/icons/company.png'),
  category: require('../assets/icons/category.png'),
  categoryOutline: require('../assets/icons/category-outline.png'),
  buy: require('../assets/icons/buy.png'),
  buyOutline: require('../assets/icons/buy-outline.png'),
  location: require('../assets/icons/location.png'),
  locationOutline: require('../assets/icons/location-outline.png'),
  edit: require('../assets/icons/edit.png'),
  arrowLeft: require('../assets/icons/arrow-left.png'),
  arrowRight: require('../assets/icons/arrow-right.png'),
  arrowDown: require('../assets/icons/arrow-down.png'),
  cirlceCheckOn: require('../assets/icons/cirlce-check-on.png'),
  setting: require('../assets/icons/setting.png'),
  search: require('../assets/icons/search.png'),
  hintArrowUp: require('../assets/icons/hint-arrow-up.png'),
  leadsMarker: require('../assets/icons/leads-marker.png'),
  sliderThumb: require('../assets/icons/slider-thumb.png'),
  cart: require('../assets/icons/cart.png'),
  groupUser: require('../assets/icons/group-user.png'),
  visa: require('../assets/icons/visa.png'),
  mastercard: require('../assets/icons/mastercard.png'),
  americanExpress: require('../assets/icons/american-express.png'),
}

export const fonts = {
  bold: 'Brown-Bold',
  regular: 'Brown-Regular'
}
